### ISSUE TITLE
Avoid label mangling in axes

### ISSUE THREAD

**Issue by v0dro** [domitry/nyaplot#31]
I create a plot (the one below) and the label names in the X axis aren't distinct. If they could be displayed partially or without overlapping, that would be great.

![plot_top_ten](https://cloud.githubusercontent.com/assets/2629909/6398816/482ef7a6-be14-11e4-9c35-fb4d60288f70.png)

**Comment by domitry** [comment]
Use `Plot#rotate_x_label` to resolve the issue.
https://github.com/domitry/nyaplot/blob/master/lib/nyaplot/plot.rb#L34-L35

**Comment by v0dro** [comment]
Thanks!

**Comment by kylekyle** [comment]
Same problem here. Is there a way to adjust the margin?
