### ISSUE TITLE
Export to more formats

### ISSUE THREAD

**Issue by agarie** [domitry/nyaplot#32]
Nyaplot can only export to HTML currently (at least that's what I found looking at the source/rubydoc).

Being able to export to other formats, e.g. PNG (even if it would mean a static image instead of the cool dynamic plots), would be useful for reports and presentations, which are my use cases.

**Comment by domitry** [comment]
Yes, Nyaplot itself cannot export plot to other formats, but nyaplot-utils enable it to export to SVG.
https://github.com/domitry/nyaplot-utils

rsvg2 will help it to export to other bitmap formats like png.
https://github.com/ruby-gnome2/ruby-gnome2/tree/master/rsvg2

**Comment by agarie** [comment]
That's great. You should put a link to Nyaplot-utils in the README showing how to create SVGs (and PNGs from it). :)

**Comment by domitry** [comment]
Nyaplot v0.1.5 enables to export plots as PNG, SVG and JPG. 
The menu will appear when you right-click on plots to save.

**Comment by agarie** [comment]
This is great news, @domitry! I'm using Nyaplot experimentally at my job, but I'll try to come up with something using open data from the Brazilian educational system to increase the number of example plots. :)

**Comment by ScientificProgressGoesBoing** [comment]
First of, thank you so much for offering this great gem!
Can you link to examples how to create png, svg and jpg? Does this only work in the IRuby environment?
