### ISSUE TITLE
Plotting sometimes doesn't work in iruby

### ISSUE THREAD

**Issue by minad** [domitry/nyaplot#43]
```
Javascript error adding output!
TypeError: ext is undefined
See your browser Javascript console for more details.
```

**Comment by v0dro** [comment]
Could you share your code?

I've observed this happen when the plot is expecting String/Symbol values and you supply Integers.

**Comment by minad** [comment]
the getting_started example notebook shows that from time to time

**Comment by domitry** [comment]
I think maybe this is related to #45
