### ISSUE TITLE
nbviewer doesn't show nyaplot output

### ISSUE THREAD

**Issue by minad** [domitry/nyaplot#45]
http://nbviewer.ipython.org/github/SciRuby/sciruby-notebooks/blob/master/getting_started.ipynb

**Comment by domitry** [comment]
I have not confirmed the mechanism yet, but it will resolved if you execute the line `require 'nyaplot'` at the end of a box on IPython.

```ruby
In [1]: 
require 'nyaplot'

In [2]:
 p = Plot.new
p.add(:scatter, (0..10).to_a, (0..10).to_a.shuffle)
p.show
```

```ruby
In [1]: 
require 'nyaplot'
print "hoge"

In [2]:
p = Plot.new
p.add(:scatter, (0..10).to_a, (0..10).to_a.shuffle)
p.show
```

The former code fragment will work properly, but the latter will not.

**Comment by lokeshh** [comment]
These facts might be useful:
- Yesterday, nbviewer wasn't working for me in Mozilla though it was working in Chrome, then I changed the `http` links to `https` links and it started working in Mozilla.
- Today, it's working in Mozilla also without changing the `http` links to `https` but only when internet speed is good. When failing Firefox web developer console gives the error `Error: Load timeout for modules: d3
  http://requirejs.org/docs/errors.html#timeout`
