### ISSUE TITLE
Ability to add multiple diagrams from the same dataframe in one shot

### ISSUE THREAD

**Issue by v0dro** [domitry/nyaplot#48]
From my knowledge of nyaplot, currently to add a new diagram (scatter, line, etc.) to the same plot from a DataFrame, user needs to use the `Plot#add_with_df` function every time. From the surface I think the DataFrame is being duplicated every time.

It would be great if it would be possible to configure the `add_with_df` method such that the diagram types and their corresponding X and Y axis columns could be specified in one shot.

Or maybe some sort of a DSL which lets you configure these options in a block, so that the corresponding Nyaplot::Diagram objects can also be configured.

**Comment by domitry** [comment]
In v0.1.x, users should specify the source dataframe each time adding new diagrams as you said.
 
```
df = DataFrame.new({hoge: [:a, :b, :c], nya: [1,2,3], hogehoge: [10, 8, 1], nyan: [0, 1, 2]})
p = Plot.new
p.add_with_df(df, :scatter, :hogehoge, :nya)
p.add_with_df(df, :line, :hogehoge, :nyan)
p.to_json
```

However, these dataframes are handled as one common object internally. 
```
"{\"diagrams\":[{\"type\":\"scatter\",\"options\":{\"x\":\"hogehoge\",\"y\":\"nya\"},\"data\":\"8e74ba5e-7b36-4f2f-9d49-bdb1423dd665\"},{\"type\":\"line\",\"options\":{\"x\":\"hogehoge\",\"y\":\"nyan\"},\"data\":\"8e74ba5e-7b36-4f2f-9d49-bdb1423dd665\"}],\"options\":{\"zoom\":true,\"width\":700,\"xrange\":[1,10],\"yrange\":[0,3]}}"
```

In v0.2.x, you can write as below:
```
Plot.from(df).add(:scatter, :a :b).add(:line, :a, :c)
```

**Comment by v0dro** [comment]
Beautiful!
