### ISSUE TITLE
changing datalabels on boxplots

### ISSUE THREAD

**Issue by tansaku** [domitry/nyaplot#56]
As far as I can see the x data labels for a boxplot default to 'data0', 'data1' etc. does anyone know how to change that?

**Comment by domitry** [comment]
```ruby
box = plot4.add(:box, arr, arr2, arr3, arr4)
box.values[:label_arr, :arr2, :arr3, :arr4]
plot4.show
```

or

```ruby
df = Nayplot::DataFrame.new({arr1: arr1, arr2: arr2})
plot4.add_with_df(df, :arr1, :arr2)
plot4.show
```

**Comment by tansaku** [comment]
awesome thanks @domitry !

**Comment by tansaku** [comment]
can't quite get that first one to work:

```undefined method `values' for #<Nyaplot::Diagram:0x007f91fc4f2f78> ```

but the second one (add_with_df) worked - woot!
